kubescape-operator:
  alertCRD:
    installDefault: false
  capabilities:
    manageWorkloads: enable
    nodeProfileService: enable
    runtimeDetection: enable
  imagePullSecret:
    server: quay.io
    username: armosec+armosec_ro
  imagePullSecrets: armosec-readonly
  kubevuln:
    image:
      tag: v0.3.142
    sbomScanner:
      enabled: true
  nodeAgent:
    autoscaler:
      enabled: true
    config:
      hostMalwareSensor: disable
      hostNetworkSensor: disable
    env:
      - name: IGNORERULEBINDINGS
        value: true
    image:
      repository: quay.io/armosec/node-agent
      tag: v0.0.276
    resources:
      limits:
        memory: 1000Mi
    sbomScanner:
      enabled: true
      image:
        repository: quay.io/armosec/node-agent
  operator:
    image:
      tag: v0.2.142
    rulesUpdateConfig:
      enabled: true
      interval: 5m
  synchronizer:
    image:
      tag: v0.0.147
  hostScannerCleanup:
    image:
      repository: quay.io/kubescape/kubectl
      tag: 1.30.3
      pullPolicy: IfNotPresent
    nodeSelector: {}
    affinity: {}
    tolerations: []
    priorityClassName: ""
