name: pull_request_created
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-created:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.17.1'

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v1.0.3

      - name: Build chart dependencies
        run: |
          helm dependency build charts/kubescape-operator/
          helm dependency build charts/rapid7-operator/

      - name: Run Helm Unittests
        run: helm unittest charts/kubescape-operator/ charts/rapid7-operator/
